import type { Genre, Permission } from "./interfaces/types.interface";

export const configData = {
  permissionGroups: {
    utilisateur: [
      "Consulter les utilisateurs",
      "Créer les utilisateurs",
      "Modifier les utilisateurs",
      "Supprimer les utilisateurs",
      "Modifier les profils des utilisateurs",
    ] as Permission[],

    paramMotDePasse: [
      "Consulter les paramètres des mots de passe",
      "Modifier les paramètres des mots de passe",
    ] as Permission[],

    connexionUtilisateur: [
      "Consulter les connexions des utilisateurs",
    ] as Permission[],

    profil: [
      "Consulter les profils",
      "Créer les profils",
      "Modifier les profils",
      "Supprimer les profils",
      "Modifier les permissions des profils",
    ] as Permission[],
  },

  genders: ["Masculin", "Féminin"] as Genre[],

  //   typesContrats: [
  //     "CDI",
  //     "CDD",
  //     "Intérim",
  //     "Freelance",
  //     "Contrat de Professionnalisation",
  //     "Stage",
  //     "Vacataire",
  //     "Fonctionnaire",
  //     "Contractuel public",
  //     "Retraité(e)",
  //     "Autre",
  //   ] as TypeContratEmploye[],

  //   situationFamilialeList: [
  //     "Célibataire",
  //     "Concubinage / Union libre",
  //     "Marié(e)",
  //     "Divorcé(e)",
  //     "Veuf(ve)",
  //   ] as SituationFamiliale[],

  //   typeIDs: ["CNI", "Passeport"] as TypeID[],

  //   moyenTransportList: [
  //     "Avion",
  //     "Train",
  //     "Bateau",
  //     "Voiture",
  //   ] as MoyenTransport[],

  nationalities: [
    { nationality: "Afghane", nation: "Afghanistan", flag: "🇦🇫" },
    { nationality: "Albanaise", nation: "Albanie", flag: "🇦🇱" },
    { nationality: "Algérienne", nation: "Algérie", flag: "🇩🇿" },
    { nationality: "Allemande", nation: "Allemagne", flag: "🇩🇪" },
    { nationality: "Américaine", nation: "États-Unis", flag: "🇺🇸" },
    { nationality: "Andorrane", nation: "Andorre", flag: "🇦🇩" },
    { nationality: "Angolaise", nation: "Angola", flag: "🇦🇴" },
    {
      nationality: "Antiguaise-et-Barbudienne",
      nation: "Antigua-et-Barbuda",
      flag: "🇦🇬",
    },
    { nationality: "Argentine", nation: "Argentine", flag: "🇦🇷" },
    { nationality: "Arménienne", nation: "Arménie", flag: "🇦🇲" },
    { nationality: "Australienne", nation: "Australie", flag: "🇦🇺" },
    { nationality: "Autrichienne", nation: "Autriche", flag: "🇦🇹" },
    { nationality: "Azerbaïdjanaise", nation: "Azerbaïdjan", flag: "🇦🇿" },
    { nationality: "Bahamienne", nation: "Bahamas", flag: "🇧🇸" },
    { nationality: "Bahreïnienne", nation: "Bahreïn", flag: "🇧🇭" },
    { nationality: "Bangladeshie", nation: "Bangladesh", flag: "🇧🇩" },
    { nationality: "Barbadienne", nation: "Barbade", flag: "🇧🇧" },
    { nationality: "Belge", nation: "Belgique", flag: "🇧🇪" },
    { nationality: "Béninoise", nation: "Bénin", flag: "🇧🇯" },
    { nationality: "Bhoutanaise", nation: "Bhoutan", flag: "🇧🇹" },
    { nationality: "Biélorusse", nation: "Biélorussie", flag: "🇧🇾" },
    { nationality: "Birmane", nation: "Birmanie (Myanmar)", flag: "🇲🇲" },
    { nationality: "Bolivienne", nation: "Bolivie", flag: "🇧🇴" },
    { nationality: "Bosnienne", nation: "Bosnie-Herzégovine", flag: "🇧🇦" },
    { nationality: "Botswanaise", nation: "Botswana", flag: "🇧🇼" },
    { nationality: "Brésilienne", nation: "Brésil", flag: "🇧🇷" },
    { nationality: "Britannique", nation: "Royaume-Uni", flag: "🇬🇧" },
    { nationality: "Bruneienne", nation: "Brunei", flag: "🇧🇳" },
    { nationality: "Bulgare", nation: "Bulgarie", flag: "🇧🇬" },
    { nationality: "Burkinabè", nation: "Burkina Faso", flag: "🇧🇫" },
    { nationality: "Burundaise", nation: "Burundi", flag: "🇧🇮" },
    { nationality: "Cambodgienne", nation: "Cambodge", flag: "🇰🇭" },
    { nationality: "Camerounaise", nation: "Cameroun", flag: "🇨🇲" },
    { nationality: "Canadienne", nation: "Canada", flag: "🇨🇦" },
    { nationality: "Cap-Verdienne", nation: "Cap-Vert", flag: "🇨🇻" },
    {
      nationality: "Centrafricaine",
      nation: "République centrafricaine",
      flag: "🇨🇫",
    },
    { nationality: "Chilienne", nation: "Chili", flag: "🇨🇱" },
    { nationality: "Chinoise", nation: "Chine", flag: "🇨🇳" },
    { nationality: "Chypriote", nation: "Chypre", flag: "🇨🇾" },
    { nationality: "Colombienne", nation: "Colombie", flag: "🇨🇴" },
    { nationality: "Comorienne", nation: "Comores", flag: "🇰🇲" },
    {
      nationality: "Congolaise (RDC)",
      nation: "République démocratique du Congo",
      flag: "🇨🇩",
    },
    {
      nationality: "Congolaise (République du Congo)",
      nation: "République du Congo",
      flag: "🇨🇬",
    },
    { nationality: "Costaricaine", nation: "Costa Rica", flag: "🇨🇷" },
    { nationality: "Croate", nation: "Croatie", flag: "🇭🇷" },
    { nationality: "Cubaine", nation: "Cuba", flag: "🇨🇺" },
    { nationality: "Danoise", nation: "Danemark", flag: "🇩🇰" },
    { nationality: "Djiboutienne", nation: "Djibouti", flag: "🇩🇯" },
    {
      nationality: "Dominicaine (République dominicaine)",
      nation: "République dominicaine",
      flag: "🇩🇴",
    },
    { nationality: "Dominiquaise", nation: "Dominique", flag: "🇩🇲" },
    { nationality: "Égyptienne", nation: "Égypte", flag: "🇪🇬" },
    { nationality: "Émiratie", nation: "Émirats arabes unis", flag: "🇦🇪" },
    { nationality: "Équatorienne", nation: "Équateur", flag: "🇪🇨" },
    { nationality: "Érythréenne", nation: "Érythrée", flag: "🇪🇷" },
    { nationality: "Espagnole", nation: "Espagne", flag: "🇪🇸" },
    { nationality: "Estonienne", nation: "Estonie", flag: "🇪🇪" },
    { nationality: "Éthiopienne", nation: "Éthiopie", flag: "🇪🇹" },
    { nationality: "Fidjienne", nation: "Fidji", flag: "🇫🇯" },
    { nationality: "Finlandaise", nation: "Finlande", flag: "🇫🇮" },
    { nationality: "Française", nation: "France", flag: "🇫🇷" },
    { nationality: "Gabonaise", nation: "Gabon", flag: "🇬🇦" },
    { nationality: "Gambienne", nation: "Gambie", flag: "🇬🇲" },
    { nationality: "Géorgienne", nation: "Géorgie", flag: "🇬🇪" },
    { nationality: "Ghanéenne", nation: "Ghana", flag: "🇬🇭" },
    { nationality: "Grecque", nation: "Grèce", flag: "🇬🇷" },
    { nationality: "Grenadienne", nation: "Grenade", flag: "🇬🇩" },
    { nationality: "Guatémaltèque", nation: "Guatemala", flag: "🇬🇹" },
    { nationality: "Guinéenne", nation: "Guinée", flag: "🇬🇳" },
    {
      nationality: "Guinéenne équatoriale",
      nation: "Guinée équatoriale",
      flag: "🇬🇶",
    },
    {
      nationality: "Guinéenne-Bissauenne",
      nation: "Guinée-Bissau",
      flag: "🇬🇼",
    },
    { nationality: "Guyanienne", nation: "Guyana", flag: "🇬🇾" },
    { nationality: "Haïtienne", nation: "Haïti", flag: "🇭🇹" },
    { nationality: "Hondurienne", nation: "Honduras", flag: "🇭🇳" },
    { nationality: "Hongroise", nation: "Hongrie", flag: "🇭🇺" },
    { nationality: "Indienne", nation: "Inde", flag: "🇮🇳" },
    { nationality: "Indonésienne", nation: "Indonésie", flag: "🇮🇩" },
    { nationality: "Irakienne", nation: "Irak", flag: "🇮🇶" },
    { nationality: "Iranienne", nation: "Iran", flag: "🇮🇷" },
    { nationality: "Irlandaise", nation: "Irlande", flag: "🇮🇪" },
    { nationality: "Islandaise", nation: "Islande", flag: "🇮🇸" },
    { nationality: "Israélienne", nation: "Israël", flag: "🇮🇱" },
    { nationality: "Italienne", nation: "Italie", flag: "🇮🇹" },
    { nationality: "Ivoirienne", nation: "Côte d'Ivoire", flag: "🇨🇮" },
    { nationality: "Jamaïcaine", nation: "Jamaïque", flag: "🇯🇲" },
    { nationality: "Japonaise", nation: "Japon", flag: "🇯🇵" },
    { nationality: "Jordanienne", nation: "Jordanie", flag: "🇯🇴" },
    { nationality: "Kazakhe", nation: "Kazakhstan", flag: "🇰🇿" },
    { nationality: "Kényane", nation: "Kenya", flag: "🇰🇪" },
    { nationality: "Kirghize", nation: "Kirghizistan", flag: "🇰🇬" },
    { nationality: "Kiribatienne", nation: "Kiribati", flag: "🇰🇮" },
    { nationality: "Koweïtienne", nation: "Koweït", flag: "🇰🇼" },
    { nationality: "Laotienne", nation: "Laos", flag: "🇱🇦" },
    { nationality: "Lesothane", nation: "Lesotho", flag: "🇱🇸" },
    { nationality: "Lettone", nation: "Lettonie", flag: "🇱🇻" },
    { nationality: "Libanaise", nation: "Liban", flag: "🇱🇧" },
    { nationality: "Libérienne", nation: "Libéria", flag: "🇱🇷" },
    { nationality: "Libyenne", nation: "Libye", flag: "🇱🇾" },
    { nationality: "Liechtensteinoise", nation: "Liechtenstein", flag: "🇱🇮" },
    { nationality: "Lituanienne", nation: "Lituanie", flag: "🇱🇹" },
    { nationality: "Luxembourgeoise", nation: "Luxembourg", flag: "🇱🇺" },
    { nationality: "Macédonienne", nation: "Macédoine du Nord", flag: "🇲🇰" },
    { nationality: "Malaisienne", nation: "Malaisie", flag: "🇲🇾" },
    { nationality: "Malawienne", nation: "Malawi", flag: "🇲🇼" },
    { nationality: "Maldivienne", nation: "Maldives", flag: "🇲🇻" },
    { nationality: "Malgache", nation: "Madagascar", flag: "🇲🇬" },
    { nationality: "Malienne", nation: "Mali", flag: "🇲🇱" },
    { nationality: "Maltaise", nation: "Malte", flag: "🇲🇹" },
    { nationality: "Marocaine", nation: "Maroc", flag: "🇲🇦" },
    { nationality: "Marshallaise", nation: "Îles Marshall", flag: "🇲🇭" },
    { nationality: "Mauricienne", nation: "Maurice", flag: "🇲🇺" },
    { nationality: "Mauritanienne", nation: "Mauritanie", flag: "🇲🇷" },
    { nationality: "Mexicaine", nation: "Mexique", flag: "🇲🇽" },
    { nationality: "Micronésienne", nation: "Micronésie", flag: "🇫🇲" },
    { nationality: "Moldave", nation: "Moldavie", flag: "🇲🇩" },
    { nationality: "Monaque", nation: "Monaco", flag: "🇲🇨" },
    { nationality: "Mongole", nation: "Mongolie", flag: "🇲🇳" },
    { nationality: "Monténégrine", nation: "Monténégro", flag: "🇲🇪" },
    { nationality: "Mozambicaine", nation: "Mozambique", flag: "🇲🇿" },
    { nationality: "Namibienne", nation: "Namibie", flag: "🇳🇦" },
    { nationality: "Nauruane", nation: "Nauru", flag: "🇳🇷" },
    { nationality: "Népalaise", nation: "Népal", flag: "🇳🇵" },
    { nationality: "Nicaraguayenne", nation: "Nicaragua", flag: "🇳🇮" },
    { nationality: "Nigériane", nation: "Nigéria", flag: "🇳🇬" },
    { nationality: "Nigérienne", nation: "Niger", flag: "🇳🇪" },
    { nationality: "Nord-coréenne", nation: "Corée du Nord", flag: "🇰🇵" },
    { nationality: "Norvégienne", nation: "Norvège", flag: "🇳🇴" },
    { nationality: "Néo-Zélandaise", nation: "Nouvelle-Zélande", flag: "🇳🇿" },
    { nationality: "Omanaise", nation: "Oman", flag: "🇴🇲" },
    { nationality: "Ougandaise", nation: "Ouganda", flag: "🇺🇬" },
    { nationality: "Ouzbèke", nation: "Ouzbékistan", flag: "🇺🇿" },
    { nationality: "Pakistanaise", nation: "Pakistan", flag: "🇵🇰" },
    { nationality: "Palaosienne", nation: "Palaos", flag: "🇵🇼" },
    { nationality: "Palestinienne", nation: "Palestine", flag: "🇵🇸" },
    { nationality: "Panaméenne", nation: "Panama", flag: "🇵🇦" },
    {
      nationality: "Papouane-Néo-Guinéenne",
      nation: "Papouasie-Nouvelle-Guinée",
      flag: "🇵🇬",
    },
    { nationality: "Paraguayenne", nation: "Paraguay", flag: "🇵🇾" },
    { nationality: "Péruvienne", nation: "Pérou", flag: "🇵🇪" },
    { nationality: "Philippine", nation: "Philippines", flag: "🇵🇭" },
    { nationality: "Polonaise", nation: "Pologne", flag: "🇵🇱" },
    { nationality: "Portugaise", nation: "Portugal", flag: "🇵🇹" },
    { nationality: "Qatarienne", nation: "Qatar", flag: "🇶🇦" },
    { nationality: "Roumaine", nation: "Roumanie", flag: "🇷🇴" },
    { nationality: "Russe", nation: "Russie", flag: "🇷🇺" },
    { nationality: "Rwandaise", nation: "Rwanda", flag: "🇷🇼" },
    { nationality: "Saint-Lucienne", nation: "Sainte-Lucie", flag: "🇱🇨" },
    { nationality: "Salvadorienne", nation: "Salvador", flag: "🇸🇻" },
    { nationality: "Samoane", nation: "Samoa", flag: "🇼🇸" },
    { nationality: "Santomeenne", nation: "Sao Tomé-et-Principe", flag: "🇸🇹" },
    { nationality: "Saoudienne", nation: "Arabie saoudite", flag: "🇸🇦" },
    { nationality: "Sénégalaise", nation: "Sénégal", flag: "🇸🇳" },
    { nationality: "Serbe", nation: "Serbie", flag: "🇷🇸" },
    { nationality: "Seychelloise", nation: "Seychelles", flag: "🇸🇨" },
    { nationality: "Sierra-Léonaise", nation: "Sierra Leone", flag: "🇸🇱" },
    { nationality: "Singapourienne", nation: "Singapour", flag: "🇸🇬" },
    { nationality: "Slovaque", nation: "Slovaquie", flag: "🇸🇰" },
    { nationality: "Slovène", nation: "Slovénie", flag: "🇸🇮" },
    { nationality: "Somalienne", nation: "Somalie", flag: "🇸🇴" },
    { nationality: "Soudanaise", nation: "Soudan", flag: "🇸🇩" },
    { nationality: "Sud-coréenne", nation: "Corée du Sud", flag: "🇰🇷" },
    { nationality: "Sud-Soudanaise", nation: "Soudan du Sud", flag: "🇸🇸" },
    { nationality: "Sri-Lankaise", nation: "Sri Lanka", flag: "🇱🇰" },
    { nationality: "Suisse", nation: "Suisse", flag: "🇨🇭" },
    { nationality: "Surinamaise", nation: "Suriname", flag: "🇸🇷" },
    { nationality: "Suédoise", nation: "Suède", flag: "🇸🇪" },
    { nationality: "Syrienne", nation: "Syrie", flag: "🇸🇾" },
    { nationality: "Tadjike", nation: "Tadjikistan", flag: "🇹🇯" },
    { nationality: "Tanzanienne", nation: "Tanzanie", flag: "🇹🇿" },
    { nationality: "Tchadienne", nation: "Tchad", flag: "🇹🇩" },
    { nationality: "Tchèque", nation: "Tchéquie", flag: "🇨🇿" },
    { nationality: "Thaïlandaise", nation: "Thaïlande", flag: "🇹🇭" },
    { nationality: "Togolaise", nation: "Togo", flag: "🇹🇬" },
    { nationality: "Tonguienne", nation: "Tonga", flag: "🇹🇴" },
    {
      nationality: "Trinidadienne-et-Tobagonienne",
      nation: "Trinité-et-Tobago",
      flag: "🇹🇹",
    },
    { nationality: "Tunisienne", nation: "Tunisie", flag: "🇹🇳" },
    { nationality: "Turkmène", nation: "Turkménistan", flag: "🇹🇲" },
    { nationality: "Turque", nation: "Turquie", flag: "🇹🇷" },
    { nationality: "Tuvaluane", nation: "Tuvalu", flag: "🇹🇻" },
    { nationality: "Ukrainienne", nation: "Ukraine", flag: "🇺🇦" },
    { nationality: "Uruguayenne", nation: "Uruguay", flag: "🇺🇾" },
    { nationality: "Vanuataise", nation: "Vanuatu", flag: "🇻🇺" },
    { nationality: "Vaticane", nation: "Vatican", flag: "🇻🇦" },
    { nationality: "Vénézuélienne", nation: "Venezuela", flag: "🇻🇪" },
    { nationality: "Vietnamienne", nation: "Vietnam", flag: "🇻🇳" },
    { nationality: "Yéménite", nation: "Yémen", flag: "🇾🇪" },
    { nationality: "Zambienne", nation: "Zambie", flag: "🇿🇲" },
    { nationality: "Zimbabwéenne", nation: "Zimbabwe", flag: "🇿🇼" },
  ],
};
